### ISSUE TITLE
Site fails on start up.

### ISSUE THREAD

**Issue by MrSalsbury** [stef-van-looveren/learning-drupal-as-a-framework#2]
I love your course.  It has given me hope that I can learn this framework! I am on chapter 2 and have learned so much. 

However, at the end of chapter 2 I am getting and error using Lando to start the site.  
I am using the included .lando.yml

lando start           
Let's get this party started! Starting app learning-drupal-as-a-framework...
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating learningdrupalasaframework_appserver_1 ... done
usermod: no changes
usermod: no changes
All settings correct for using Composer
Downloading...

Composer (version 2.2.12) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Changed current directory to /var/www/.composer
./composer.json has been created

Installation failed, deleting ./composer.json.

In Factory.php line 334:
                                                              
  "./composer.json" does not match the expected JSON schema:  
   - require : Array value found, but an object is required   
 
Can you give me a suggestion on how to work around this error.  Any help is greatly appreciated.

Thank You

**Comment by MrSalsbury** [comment]
I changed the .lando.yml from composer: 2 to "composer_version: '2.0' and although it says "ERROR ==> The defined install version (2.0) does not match release pattern."  the site starts up pulls in the configurations and appears to be working.

**Comment by stef-van-looveren** [comment]
Thanks, I updated the yml file. Sorry for my late response, have been busy!
